/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.login;

import java.awt.Color;
import javax.swing.*;

/**
 *
 * @author User
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }
    public void actualizarMensajeBienvenida(String nombre) {
        bienv.setText("¡Bienvenido, " + nombre + "!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        icono = new javax.swing.JLabel();
        imagentext = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        bienv = new javax.swing.JLabel();
        namelogo = new javax.swing.JLabel();
        iconolog = new javax.swing.JLabel();
        eliRP = new javax.swing.JLabel();
        agrRP = new javax.swing.JLabel();
        modRP = new javax.swing.JLabel();
        verRP = new javax.swing.JLabel();
        busRP = new javax.swing.JLabel();
        exitB = new javax.swing.JPanel();
        exitBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icono.setBackground(new java.awt.Color(255, 255, 255));
        icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Logos Servicio Técnico Simple Blanco y Negro (1).png"))); // NOI18N
        jPanel1.add(icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 230, 170));

        imagentext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/image.png"))); // NOI18N
        jPanel1.add(imagentext, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, -1));

        jPanel2.setBackground(new java.awt.Color(43, 43, 61));

        bienv.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        bienv.setForeground(new java.awt.Color(255, 255, 255));
        bienv.setText("Bienvenido");

        namelogo.setFont(new java.awt.Font("Roboto Black", 2, 14)); // NOI18N
        namelogo.setForeground(new java.awt.Color(255, 255, 255));
        namelogo.setText("PARTENGINE");

        iconolog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/image (1).png"))); // NOI18N

        eliRP.setFont(new java.awt.Font("Roboto Medium", 2, 18)); // NOI18N
        eliRP.setForeground(new java.awt.Color(153, 153, 153));
        eliRP.setText("2.- Eliminar Repuesto");
        eliRP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliRP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliRPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eliRPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eliRPMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                eliRPMouseReleased(evt);
            }
        });

        agrRP.setFont(new java.awt.Font("Roboto Medium", 2, 18)); // NOI18N
        agrRP.setForeground(new java.awt.Color(153, 153, 153));
        agrRP.setText("1.- Agregar Repuesto");
        agrRP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agrRP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agrRPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                agrRPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                agrRPMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                agrRPMouseReleased(evt);
            }
        });

        modRP.setFont(new java.awt.Font("Roboto Medium", 2, 18)); // NOI18N
        modRP.setForeground(new java.awt.Color(153, 153, 153));
        modRP.setText("3.- Modificar Repuesto");
        modRP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modRP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modRPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                modRPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                modRPMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                modRPMouseReleased(evt);
            }
        });

        verRP.setFont(new java.awt.Font("Roboto Medium", 2, 18)); // NOI18N
        verRP.setForeground(new java.awt.Color(153, 153, 153));
        verRP.setText("5.- Ver Repuestos");
        verRP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        verRP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verRPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verRPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verRPMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                verRPMouseReleased(evt);
            }
        });

        busRP.setFont(new java.awt.Font("Roboto Medium", 2, 18)); // NOI18N
        busRP.setForeground(new java.awt.Color(153, 153, 153));
        busRP.setText("4.- Buscar Repuesto");
        busRP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        busRP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                busRPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                busRPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                busRPMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                busRPMouseReleased(evt);
            }
        });

        exitB.setBackground(new java.awt.Color(102, 51, 255));
        exitB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitBMouseExited(evt);
            }
        });

        exitBtn.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        exitBtn.setForeground(new java.awt.Color(255, 255, 255));
        exitBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitBtn.setText("SALIR");
        exitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBLayout = new javax.swing.GroupLayout(exitB);
        exitB.setLayout(exitBLayout);
        exitBLayout.setHorizontalGroup(
            exitBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        exitBLayout.setVerticalGroup(
            exitBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(modRP, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(bienv)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 261, Short.MAX_VALUE)
                                .addComponent(namelogo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(iconolog)))
                        .addGap(47, 47, 47))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(busRP, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agrRP, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eliRP, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(verRP, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namelogo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconolog, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(bienv)
                .addGap(47, 47, 47)
                .addComponent(agrRP, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eliRP, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modRP, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(busRP, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(verRP, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(exitB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 510, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eliRPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliRPMouseClicked
      
    }//GEN-LAST:event_eliRPMouseClicked

    private void eliRPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliRPMouseEntered
        eliRP.setForeground(new Color(242, 242, 242));
    }//GEN-LAST:event_eliRPMouseEntered

    private void eliRPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliRPMouseExited
        // [153,153,153]
        eliRP.setForeground(new Color(153, 153, 153));
    }//GEN-LAST:event_eliRPMouseExited

    private void eliRPMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliRPMouseReleased

    }//GEN-LAST:event_eliRPMouseReleased

    private void agrRPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agrRPMouseClicked
        RepuestoCRUD crud = new RepuestoCRUD();
    
    // Mostrar un cuadro de diálogo para que el usuario ingrese el nombre
        String nombre = JOptionPane.showInputDialog(this, "Ingrese el nombre del repuesto:");
        if (nombre == null || nombre.isEmpty()) {
        JOptionPane.showMessageDialog(this, "El nombre no puede estar vacío.");
        return;
    }

    // Mostrar un cuadro de diálogo para que el usuario ingrese el precio
        String precioStr = JOptionPane.showInputDialog(this, "Ingrese el precio del repuesto:");
    try {
        // Convertir el precio a un número
        double precio = Double.parseDouble(precioStr);

        // Crear y agregar el nuevo repuesto al CRUD
        Repuesto nuevoRepuesto = new Repuesto(nombre, precio);
        crud.agregarRepuesto(nuevoRepuesto);

        // Mostrar un mensaje de confirmación
        JOptionPane.showMessageDialog(this, "Repuesto agregado exitosamente:\n" + nuevoRepuesto);
    } catch (NumberFormatException e) {
        // Manejar el caso en que el usuario no ingrese un número válido
        JOptionPane.showMessageDialog(this, "Por favor ingrese un precio válido.");
    }
    }//GEN-LAST:event_agrRPMouseClicked

    private void agrRPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agrRPMouseEntered
        agrRP.setForeground(new Color(242, 242, 242));
    }//GEN-LAST:event_agrRPMouseEntered

    private void agrRPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agrRPMouseExited
        agrRP.setForeground(new Color(153, 153, 153));
    }//GEN-LAST:event_agrRPMouseExited

    private void agrRPMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agrRPMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_agrRPMouseReleased

    private void modRPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modRPMouseClicked
       
    }//GEN-LAST:event_modRPMouseClicked

    private void modRPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modRPMouseEntered
        modRP.setForeground(new Color(242, 242, 242));
    }//GEN-LAST:event_modRPMouseEntered

    private void modRPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modRPMouseExited
        modRP.setForeground(new Color(153, 153, 153));
    }//GEN-LAST:event_modRPMouseExited

    private void modRPMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modRPMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_modRPMouseReleased

    private void verRPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verRPMouseClicked
        
    }//GEN-LAST:event_verRPMouseClicked

    private void verRPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verRPMouseEntered
        verRP.setForeground(new Color(242, 242, 242));
    }//GEN-LAST:event_verRPMouseEntered

    private void verRPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verRPMouseExited
        verRP.setForeground(new Color(153, 153, 153));
    }//GEN-LAST:event_verRPMouseExited

    private void verRPMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verRPMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_verRPMouseReleased

    private void busRPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busRPMouseClicked
      
    }//GEN-LAST:event_busRPMouseClicked

    private void busRPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busRPMouseEntered
        busRP.setForeground(new Color(242, 242, 242));
    }//GEN-LAST:event_busRPMouseEntered

    private void busRPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busRPMouseExited
        busRP.setForeground(new Color(153, 153, 153));
    }//GEN-LAST:event_busRPMouseExited

    private void busRPMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busRPMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_busRPMouseReleased

    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked

        login salircambio = new login();
        salircambio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_exitBtnMouseClicked

    private void exitBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseEntered
        exitB.setBackground(new Color(156, 106, 208));
    }//GEN-LAST:event_exitBtnMouseEntered

    private void exitBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseExited
        exitB.setBackground(new Color(102, 51, 255));
    }//GEN-LAST:event_exitBtnMouseExited

    private void exitBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBMouseClicked

    }//GEN-LAST:event_exitBMouseClicked

    private void exitBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBMouseEntered
        exitB.setBackground(new Color(156, 106, 208));
    }//GEN-LAST:event_exitBMouseEntered

    private void exitBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBMouseExited
        exitB.setBackground(new Color(102, 51, 255));
    }//GEN-LAST:event_exitBMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agrRP;
    private javax.swing.JLabel bienv;
    private javax.swing.JLabel busRP;
    private javax.swing.JLabel eliRP;
    private javax.swing.JPanel exitB;
    private javax.swing.JLabel exitBtn;
    private javax.swing.JLabel icono;
    private javax.swing.JLabel iconolog;
    private javax.swing.JLabel imagentext;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel modRP;
    private javax.swing.JLabel namelogo;
    private javax.swing.JLabel verRP;
    // End of variables declaration//GEN-END:variables
}
